spring:
  datasource:
    url: jdbc:mysql://localhost:3306/activiti6?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: 111111
    driver-class-name: com.mysql.cj.jdbc.Driver
